### ISSUE TITLE
How to generate a ref_points.sdf file from my complex pdb file?

### ISSUE THREAD

**Issue by Lumen97** [oxpig/MolSnapper#1]

**Comment by Lumen97** [comment]
After running prepare_single_complex.py and clean_and_split.py, the following files are obtained: 
8azz_0.sdf, 8azz.pdb, 8azz.pkl, 8azz_protein.pdb. 
However, running sample_single_pocket.py requires ref_points.sdf.

**Comment by Lumen97** [comment]
This file is manually selecting the pharmacophoric atoms of the ligand and saving them as an SDF file.

**Comment by YaelZiv** [comment]
Hi, now that you have the files for the ligand and the pocket, you should decide on your reference points that will guide your generation. You can do this manually, and it may vary depending on your goal. For example, you can use PyMOL to choose certain atoms that will define the overall shape of the ligand or select atoms that form specific interactions. Another option is to extract pharmacophore points, which is supported in the code.
