### ISSUE TITLE
The difference between 0.sdf and 0_shifted.sdf

### ISSUE THREAD

**Issue by Kartinaa** [oxpig/MolSnapper#2]
Dear authors,

Thank you for sharing your wonderful work—it’s really intriguing. I’d like to understand the difference between the `0.sdf` and `0_shifted.sdf` files after I sampled molecules for a customized pocket. Were any post-processing methods applied to generate the `0_shifted.sdf` file?

Thank you for your time, and I’d really appreciate any clarification you can provide.

Best,
Bo

**Comment by Kartinaa** [comment]
Also, I encounted an error when trying to sample molecules from Crossdock dataset. I have downloaded and processed Crossdock dataset, the sampling command is `python scripts/sample.py --outdir ./outputs --config ./configs/sample/sample_MolDiff.yml --batch_size 32 --pocket_dir CrossDocked_test  --num_pharma_atoms 20 --clash_rate 0.1
` and the error I had is ` File "MolSnapper/scripts/sample.py", line 121, in <module>
    with open(os.path.join(args.pocket_dir, 'filetered_uuid.json'),
FileNotFoundError: [Errno 2] No such file or directory: 'CrossDocked_test/filetered_uuid.json'
`
Many thanks!

**Comment by YaelZiv** [comment]
Hi Bo, the only difference between the 0.sdf and 0_shifted.sdf files is in their centering. The 0.sdf file is centered at zero (0,0,0), while the 0_shifted.sdf file has been shifted back to the original center of the pocket. No other post-processing methods were applied—this shift simply repositions the molecules in relation to the original constrains' spatial coordinates.

In addition, the file 'filetered_uuid.json' is in data/crossdocked/ please move it to your data directory
best,
Yael

**Comment by Kartinaa** [comment]
Thanks so much Yael, it helps a lot!
